include: package:flutter_lints/flutter.yaml

formatter:
  trailing_commas: preserve

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    avoid_print: true
    prefer_single_quotes: false
    prefer_double_quotes: true
    always_specify_types: true
    await_only_futures: true
    no_logic_in_create_state: true
    non_constant_identifier_names: false
    prefer_null_aware_operators: false
    use_build_context_synchronously: false
    constant_identifier_names: false
    camel_case_types: true
